.PHONY: clean All

All:
	@echo "----------Building project:[ exercise_1_2 - Debug ]----------"
	@cd "exercise_1_2" && "$(MAKE)" -f  "exercise_1_2.mk"
clean:
	@echo "----------Cleaning project:[ exercise_1_2 - Debug ]----------"
	@cd "exercise_1_2" && "$(MAKE)" -f  "exercise_1_2.mk" clean
