.PHONY: clean All

All:
	@echo "----------Building project:[ example_1_5_1_3 - Debug ]----------"
	@cd "example_1_5_1_3" && "$(MAKE)" -f  "example_1_5_1_3.mk"
clean:
	@echo "----------Cleaning project:[ example_1_5_1_3 - Debug ]----------"
	@cd "example_1_5_1_3" && "$(MAKE)" -f  "example_1_5_1_3.mk" clean
