.PHONY: clean All

All:
	@echo "----------Building project:[ LambdaParametersandReturnType - Debug ]----------"
	@cd "LambdaParametersandReturnType" && "$(MAKE)" -f  "LambdaParametersandReturnType.mk"
clean:
	@echo "----------Cleaning project:[ LambdaParametersandReturnType - Debug ]----------"
	@cd "LambdaParametersandReturnType" && "$(MAKE)" -f  "LambdaParametersandReturnType.mk" clean
