.PHONY: clean All

All:
	@echo "----------Building project:[ RValueReferences - Debug ]----------"
	@cd "RValueReferences" && "$(MAKE)" -f  "RValueReferences.mk"
clean:
	@echo "----------Cleaning project:[ RValueReferences - Debug ]----------"
	@cd "RValueReferences" && "$(MAKE)" -f  "RValueReferences.mk" clean
