.PHONY: clean All

All:
	@echo "----------Building project:[ ColorTransforms - Debug ]----------"
	@cd "ColorTransforms" && "$(MAKE)" -f  "ColorTransforms.mk"
clean:
	@echo "----------Cleaning project:[ ColorTransforms - Debug ]----------"
	@cd "ColorTransforms" && "$(MAKE)" -f  "ColorTransforms.mk" clean
