.PHONY: clean All

All:
	@echo "----------Building project:[ example_2_2_4 - Debug ]----------"
	@cd "example_2_2_4" && "$(MAKE)" -f  "example_2_2_4.mk"
clean:
	@echo "----------Cleaning project:[ example_2_2_4 - Debug ]----------"
	@cd "example_2_2_4" && "$(MAKE)" -f  "example_2_2_4.mk" clean
